canonical: https://krebsregister-rlp.de/fhir/tumorboard
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: Implementierungsleitfaden Tumorboard
name: Implementierungsleitfaden Tumorboard
status: draft
version: 0.0.1-work
publisher:
  name: Krebsregister Rheinland-Pfalz gGmbH
  url: https://www.krebsregister-rlp.de/
  email: info@krebsregister-rlp.de
dependencies:
  de.basisprofil.r4: 1.4.0
