# This is a basic workflow to help you get started with Actions

name: IG Publisher

# Controls when the workflow will runa
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ghcr.io/echinos-eu/hl7-ig-builder-docker:release

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Update the image to the latest publisher..."
          # Get the latest publisher - don't run the batch script but run the line directly
          curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o ./input-cache/publisher.jar --create-dirs
          fhir install de.basisprofil.r4@1.4.0
          echo "Run the IG publisher..."
          ls -lahs resources
          java -jar ./input-cache/publisher.jar publisher -ig resources
          unzip output/full-ig.zip -d upload/
